def SUBSTRING(text, i, k):
    return text[i:i+k]

def COUNTER(text, k):
    counter = {}
    for i in range(len(text) - k + 1):
        substring = SUBSTRING(text, i, k)
        counter.setdefault(substring, 0)
        counter[substring] += 1
    
    return counter

text = 'ATAACCATTGAACGCCTGAACGCCTGGTATTCCTTATAACCATTGGATATGGCAGTATGGTTCCTGATATGGCAGGTATTCCTTAACGCCTGGATATGGCAGAACGCCTGTATGGTTCCTGATATGGCAGTATGGTTCCTGATATGGCAGGATATGGCAGATAACCATTGTATGGTTCCTGTATTCCTTGTATTCCTTGATATGGCAGTATGGTTCCTATAACCATTGGTATTCCTTGTATTCCTTATAACCATTGTATGGTTCCTAACGCCTGGATATGGCAGAACGCCTGGTATTCCTTGTATTCCTTAACGCCTGATAACCATTGATAACCATTGTATGGTTCCTATAACCATTGTATGGTTCCTGTATTCCTTATAACCATTGGTATTCCTTGTATTCCTTAACGCCTGGTATTCCTTAACGCCTGTATGGTTCCTAACGCCTGGTATTCCTTAACGCCTGGATATGGCAGGATATGGCAGGATATGGCAGGTATTCCTTGTATTCCTTATAACCATTGAACGCCTGAACGCCTGATAACCATTGGATATGGCAGATAACCATTGGATATGGCAGGTATTCCTTTATGGTTCCTTATGGTTCCTGATATGGCAGATAACCATTGGTATTCCTTATAACCATTGTATGGTTCCTGATATGGCAGATAACCATTGATAACCATTGATAACCATTGATAACCATTGAACGCCTGATAACCATTGGATATGGCAGGATATGGCAGAACGCCTGGTATTCCTTGTATTCCTTGTATTCCTTTATGGTTCCTTATGGTTCCTTATGGTTCCTAACGCCTGTATGGTTCCTATAACCATTGGATATGGCAGGATATGGCAGAACGCCTGTATGGTTCCTAACGCCTGGTATTCCTT'
k = 12

counter = COUNTER(text, k)
max_frequent = [key for key in counter.keys() if counter[key] == max(counter.values())]

print(' '.join(max_frequent))