def SUBSTRING(text, i, k):
    return text[i:i+k]

def COUNT(text, pattern):
    count = 0
    k = len(pattern)
    for i in range(len(text) - k + 1):
        if SUBSTRING(text, i, k) == pattern:
            count += 1
    
    return count

text = 'TGTAGGAGGGTATAAGGGTATAGGGTATAGCAAATTCAGGGTATAGAGGGTATCAGGGTATAGGGTATCAGGGTATAAGGGTATGGCGTTGAGGGTATAGGGTATAGGGTATTAAGGGTATCATGTAGGGTATGAGGGTATCTCAGCAGGTTAGGGTATAGGGTATAGGGTATCAGGGTATCAGGGTATGTCCTGTAGGGTATCTCCTTCTGCCATACAGGGTATTGAGGGTATAAGGGTATTAGAGGGTATGAGGGTATCAGGGTATAGGGTATCCGCAGGGTATAGGGTATCAGAAGGGTATTGAGGGTATTCCAAGGGTATAATAAGGGTATCTAGGGTATCGAGGGTATAACGTTAGGGTATTTCAGGGTATCAGGGTATAAGGGTATCAGGGTATCTAGGGTATAGGGTATCAGGGTATCACTCCAGGGTATCCAGGGTATTCAATAGGGTATAAGGGTATGTGGAGGGTATCAGGGTATGGTGTAGGGTATCGAGGGTATTAAGCAGGGTATAAAGGGCGGATAAGGGTATACGAGGGTATTAAGGGTATAGGGTATTCAGGGTATTGCGAGGGTATAAGGGTATAGGGTATCAGGGTATATTTGACCAGGGTATTGAGGGTATCCAAAAGGGTATAAAGAGGGTATAGGGTATGTAGGGTATGAGGGTATCAATTGTAAGTGAGGGTATCAGGGTATCCTAGGGTATCATTTTTTAGGGTATCAGGGTATAGGGTATAAGGGTATAAGGGTATGAGGGTATAGGGTATTACTAGGGTATAGGGTATTGAGGGTATAGGGTATTTGAAGGGTATAGCAGTACAGGGTATTACGTAGGGTATCACCTGCGAGGGTATTTAAGGGTATGAGGGTATTAGGGTATGCCAGGGAGGGTATAAGGGTATCAGGGTATAGGGTAT'
pattern = 'AGGGTATAG'

print(COUNT(text, pattern))