sInput1 = '''
4
4->CAAATCCC
4->ATTGCGAC
5->CTGCGCTG
5->ATGGACGA
6->4
6->5
'''

sInput1_1 = '''
4
4->CAA
4->ATT
5->CTG
5->ATG
6->4
6->5
'''

sInput2 = '''
128
128->GCCCCATTTAGTGTCAACACGCGACTAAATTCCCACATCACATTGTATTCGTCTCGAAGTTGGCCGCGAGACGATGCGAGGTCTGGGGCTCAGGCACACTCCAGTCGCTATTGGAGCTTTGCTGGCGTTGTCATGTTAGGAAACTAACCT
128->AGGACCCGATTCACGTCAATGGATGGATGTCTTTTCAAACGCTTTCCGTTTATATACACACGGGTACCAAACACCCGAGACGTTGTTCCTTTTAACTTGCACCATCGGAATAACGGCAAATTCTTTGAGTGTCGGGGGCCTACCTAGGTC
129->ACATACGTTCCACGTCAAGGGCGTGAGCCTTGGGGGTGGGGTCTTCTCCTACTTGTTCATATTGATACAAAAATGGTGACCAGCAAGGATCCGCTAGGTCACAGAATGTTCAGGCTAAGACTTTATTGTATTTACACCCGCCTTCACAGC
129->TTCAAGCGACTTTTTAAGTTCAAAGTCTTTGATCTTTCTCGTCTTTATAACCAGGAAAGTAGTACAACCGGAGCGATTCTTGAAGCACTCCAATATTGTAAGGACCTTCCTATAAGCAGCCAACCGTCCCCCCCTAAGTTTTCATTGCGT
130->AGCCCCACACGATGGCATTAACAACATCCCTTTGACGATCATAGTAACAAGCCTGCCCCTAACAAGTACTTAAATAGCGACCTCATAATCCTTCGTCCTAAACATGGGACCCAGTTTGGTGCATGCATTCAGATAGTACAGAATCTGGTG
130->GCTGCCGCGCCAGTTAGGCGTGATGCCCCAGAATAGCAAGAAATCCTGCTCTTGACACCGGCGACGCATCAAGCACTCCGCCAAGGTCAAGTCGCCACGAGTCGGGGACACTATGTGCGTTACCGCATCTTATATACTATACATGATGTT
131->TCCGGTTCACTAGGGCCATGAAGTTATGTATTGCGTTGCCGTGACTTGCTTCCCTGTAAAGTTCTCCTGACCTACTCATCATTCGCGTGGAAGGTTGACTGTGGAAACGGTATAAGTTGCATTCCGACGGGTGTTTTATGCGTCGGCCAC
131->GGACTTGACTGTAACACTAAACAGAGGGCCAGAATATGGGGTCAGAACCCACGTAGCTGCCTCAAAGGAAGTCGCAGGGTTCGGTTGGTAGCTTCGGTTCCGTTTTGATATTGCGCGACACACCTGCACGCGCGCATCTACGATGCTGCA
132->GTGTACGAATAAAAACTGTACGGTGTGCGTCTAGACGAGCCGAAGTAACTACACATAGAACGTCCCTACGATCGTGACTCAGTGATGACCTTTGTGCAGAGTGGCAGCCCCGGTAGTGAGCGGACCCTAGGTTAAGTACCCTGTACCCCG
132->TTCTCTAGCCAGTTTCTGCAAACACTCTACAGAAAAAAAGTAATCCCCACAATCCTAATTTGACGATGATATGCGGAAGCCGTTCAAGAGATACGTGCCTAGCTGGAATGTTCAGCTTGGTCGTTTCACCTTTATGTCCCTCCGAATCGA
133->TAACGCACATTAGAAATAGGTAGCGGTAAGAGCCCGGGATGAATTCACGGAACTGCACGGCAAGATTTGTACCGATATTTCCTACCGGGCTGAGTGATTGTTGATAAATCCTGATGACCATGAAGAGGCTCTCAGATCTTAGGGAGGTAG
133->TCATTATCGCCGTGTGTTCGCCATGGCTCTGAACCCACACGTGGCGATGCGTGCTTCCATATATCTGTCCTTCTTTGGCTGGGTCTGTGCAGCAATCGTAAGGTTCCCTCCTGAGGGGGTATCGTGGCGGGAGCTATGCATCGGAATAGA
134->GCTCTTTATTAGGAGTTAAGACGTAACGGACTGGAAAACTCGAGTAAGCGCTGGTCCCTTATTAACGGTCAGGATTGCCGTCCTTAAGCCCGGTTGGAGTTCTTAACATAACGGGATCAGGGACTTAATCGAAAGGCGTACCTCTGTATC
134->TACCATTACAGCCGTGTACTCGGCAAGACGAGTAGAGGACTCCGGACCGAGGGCTTGCCGGCGTTGGTGAAGCCCGGGAGTTTCGGGAAGATTCTGTCAAGGAGAACACCTTTCGAAGCAGAATATATGAGAACAAAGACTCCGCTGGTC
135->TGCATATGCATTTACCCTGGTATAAAGGTTGCTCGCTTATTCCTTGCGCGATTTATCCTGGTTCGCAAAGAAACTAGCCGAGATTGGCAAGTAAAGAAGCGTCAAAACTACGGGAGCACCATGGGCTTTTCTAGTAGATGAAATGATAGT
135->GTGCGATCGATCCTCACAAAGCGCAGGTAGCGCGAGTTGACCGCCCTGTAAAAGGCCCTATGCCTGCGTTGTTGCTTTAGCCGGAAGCCATCTAGCACTGAACGAGGGCATCGGACACCTGATGATTATACCGGTGATAAACAGGATGGC
136->TACGTATTTTACACCGATCGTCAGCAGGTTCCTTCTGCGCGGTCGTCAGCAGTAACTCGGCAGGCCCCCGACCACTACTTGAGATATGAAATCACGTGGGACTACTAATGATACAGGGTGACACCGATTGTAATGGCACGATTTTCCTTC
136->CGCACCATATCATATCCCGTGTTTGCATCGCCAACACCCTAAGTAGGTCTGTGGGAGCGCAACTGCGTCCGTGGCAATCTAATATACCCAATGGGCAATTCGTACCTTCCTTTAACTAACCACTGAAGTCTCTTTCATCAGTTCTTGAAA
137->AATGCCAAGCCCTGAAGGTATCTGCTCTTGAGCGGCACAGGTATTCGCTATAGCGTGCTAAAGGACCTTCACACAGGATCTAGGTGGCCGAATATTTGATAAAAGAGCTAGCACCCTTGGGCGGTTTTTTCCCTGCCTGGTTCCGTCCGT
137->AGAATCACTAAAGGCCTATAACCGTTCCTTTGGCCTCACTCAAGCGGATTAAGGCAAGGTGTTCTGACGAGTTGCCCTCCTAACAATTATATGGGTATCGCGTAACCGATTTTTGGCATGGACCCGTCGCTGTAATGAAAGAGGGCTAGT
138->CGGAACAATATTCACGTTTATGTCTCGCCAAAGTGGCTACACGACGCCGAGCCCGTGGGCTTACGACCCCCAAGCAAGCACCGAATTGTTACTACGTGCTCCGTGTCCCACGAGTCCCAACCTAGTGCCGACCTCATAGACATGCGTCAT
138->GCGGCTATCCTCATAAGGTGACAGCTCTTCAGTTTCACACGAGTAATATAGTCATTTGGGCGGGGACCGGAAAGGGGCCGCGAACAGACCAGGAAAGTAGACTAGCGCCTGTCTGATGTGCAACAAGGCGCCGATGGAAGTTCCTCTGCG
139->ATCGCTACCATGACACGTACCCCGACGATGCTGGGATGATATCGAGACTCCTTCCCTATTTTAAACAAACAAGTGAGTGGCGCCTGAGAAACGAGTGGCAGCAGCAGGCCGCTCCAGACTAGGTCCATCCGGAGTGTCAAACCAGGGACG
139->GTCGTTAACGCTACCTCGTATATTAATCGAGGTTGTATCAATGGTAGTACTATGGTCGGTGTAGCCCTGATGCCCGAGACTATCAACGCTTGCGTTTAAAGATATATTGCATGATCATCGCATTCGTACCCTATAGACTAAAATGGACAA
140->TGGAGTCCGCTCACCTTGAATTCGCGCAGCCACTTTGACACACATAACCGCACAGGATAACATCACGATCCCTACCCCGGCTGACTCACCACATTGTCGACTGTGATCCGACGCAAAATTAAATTCTCGTGTCTGCCTCTATCTCTCTGG
140->GCGTAATTTGGGGACCCTTCCTACGGCAGTTCTAGACAGGAAACCCCCCCTTTGGTCGTGGAAACCTCCAGAACACACAGAAGCTGGCGGTACGTAGTTGAGTTCGCTCGCTGCCTTAGAACCTACAATATTGGGAAATGGTGAGTCATC
141->CGCAGGCGCAATTTTGGAGATCAGGATCTTGGGAACTGCTAGGTGGGATCATCGCGGGGAAGTTAACGAGGCGGACGCTGTGCTTGAGGACAGCAGGCAGCTATTTACCCGCGACCCTCCCTGGGTAGATTCGCATCGCTGACTTGTCAT
141->CGGGCATATACCGTTTCTTACTAATTTGGGTAGGTCAATATATGACTGGACCATCGGACTTTGTAAATTACGGGATCTAACTCCTATGAGTTCTCCCAGGGCTCGGTGTGAAACAAACGAGTGCGGAACCCGTGTCGGCGCTTTTCCGTA
142->AGCCATAACTGATATAGTCTGTAACACGATACGATACGAATCTGAAGACTTCTAATTGTATTATAGTCTTACGTAGATGCAGGTGGTCCCGTGTCTGTAACTTCACCTATCACCCTTCAAGCTCAATGTCGGACAGTACGTGAGCTCTTA
142->GGTATATACCACCGTCTTCCCCATTGTAAACCGCCCCTCGCCCCGTGTTGTGCTTATATCGTCTCGCGCTCGGAAACAGTGATCTTGGTCACATGGTAACGCTCAGGGAGGTCGCATTGAGTTACGCTAGATATCCCAGATACCGTGTGG
143->TCCGCGCATGCGGTGAAATAGCAAAGATTGGTCCCTCACTCCTTAACGTAGATTTTGTACTCTAAAAGGCAACTCAACCGGTCGAAAATGCAAACCGAGACAGGGACTGTGCCGGAGTATGCCCGGAGTTGGTATCATGAATCCAGGTTA
143->GAGTTCGTCTTGTCAAAAGGGAGACGAGAGTATTTGCCCTCAGCGCGGCGCGGCTCAAGCTGACTACGAGTCAATTAAGGGTATACCTATGAAGCCCCCTGGGTGCTCTGAGTTTGCTTGGAAGACAGTGCAGCCCGATGGTGGTACAAC
144->GTTAAAGGTCGCCGATGTGCTCGATAAATCCTCTGTGAAGTGGAGGAATCATCTGGCCAATCCTTATTGCGAAACCAGTTGGTTTATGCGATCTTGTGGAGAAGGCGCGCAGAAGCTTGGAACTATCCTGTCTAGGTTATATCCTACGAA
144->CTGGTGGTTGCGTCAGGTAAACACAATGACGCCAGGGCGTTATGCGGTCTGGTTTAATGCTAGCGACATCGGTCTGATGTTCTTCGAGGGTTACGTCTTGGTCTGGCGTGTAGAGTGGGCTTGTCCCTATAGATGAAGCTGTTTGTGTAC
145->GCCTCCTATAAATAAGATTACACCCAGAGCTCAGGCTCAGCGTCGCTCCAAAGCAAGTCAAGATCGAGTTTCCCGAATAATTCCACGGTAGAAGCCTATCACTTGTCCTACAATAGAAGCTTCGCGTATCCCGGGCATGGAGAAATTCGG
145->CGCTACTTGCAGAAACGTGCTTTGATATAACCCCGGATAACTCAAACCTTACGTATCCTGCGTCTCGTTTCCGATACTTACAGTTCGCACGCGTTGGAGTGGAGTGACCTGCGGGGTATAGAGTACGAACGCTATGTTTACCAAGCTCTC
146->CGCATTCTCACTACTCCGCCTATAATACGTCGAATAGCAACTATCTGCGCCTTTGTAACGCGTGCTGGGCGACGGCCTATACTGGATTCTTTACTGAATCCTTAGAGCCTGTACCATATACTGAACGTCTCCCCCCCTGTTTATATTTTC
146->CGACCATACATCAGAGGAGAGTGTAATTATTAGTTGTAGGAAGACAATAGACAGCCCCGAATCTCCCGGATCCCCAGTGTATATGAAGAATTATACCTGCTGGTAGCATTACCTTTACTCACCATCAGGGAAACTTCGTAGGTGCGGGAC
147->CGCATCGCATACCTATGGTCCGCCACATTTCACATTGATGAATGATGAGTGGTCTGCATCGAGACAGCCTAGGCAATGTTTGAAAGTGTGAGTACCCGTCGTTTGGGTTCATATTACATCACTGTTTAGCGCATCTCACGGCGAAGGATC
147->TTAGCTGACGTGGAAACAGCGGGCCGCATCGCGGCCATTCCGGGCCAAACTTTGGAATAATGTAAGCGGAAGTCGTTAAAGAGTCGATAGGGGACTATCTTGTTCCACCGTCTGAAGCCGCCTCGAGGCCTCCGATTCGCGAAAAACCGG
148->CTTTAAGATCTTTTTAACCCACTCCTGCGATGTTTCAGCGAGAGGGCAGTCTCCCGTGAAGCAAGCCTCGAAATGTAGGATACGCGGTCGGGCGCAACGGCGTCGGTGTTGCTAATGGCGATAGTGTGCACATCCGGTGACCCTTGGCAC
148->CAATACAGTTAATGTCTTGTCTTAAAGAGTTTCCTGTTCTAAATGGTATTTGCTATTCTGCCTTGCTTTCACCAAAAGGCGATGGGCCTCTAGATAACCATAGAATCTACCGAAGATTACCTCGTACCTACGCTTGTATATGTGCAAATA
149->TCTTCCCAATCTTGTCGAGCCGTGGATTATTGCCCCAGGACTAATCCTAGTCACACATAACTTAAGACGTCCCCTGGGGTTGATTTTATAAATACGGTCAGGGGCTAGAGTTGGTCTAACTCGTAGTTTCACGTCCGGGCATTAAATCGG
149->ATAGTTATCTGGCAGAGCGCCCTTAGTTGCTCTGCTTACTTTATGACTCACCTTGGGTCGCCCGTACGTTCGGTCACTCTCTTGGTCACCAGGGGAACTCAGGAATTTAGAAAGCGAGGGTAATTAGTTTCTAGTGTGGACATTACAGCA
150->AAACGGGGACTCGTTGTGGAGGCTTACCTTGCGCTGAGGCGTAGTTGAGTGCTCCGTAGCTGCACATGTTCGGGAAAAATAGGCATCTCCTCGATGCTCGTACTTAGCAGTCCCTCGGGTTTCTGTTTAAAGCCGTCTCACTGTGTTTTT
150->AAAATTGCAGTGAGCTTCCGGTTCGGGCTTGGTGGAAAAGTTCTCTGTATTACTGGCTGTTCAAGCCCTTGCCAACGAACGGTTTGATAGCTAAGCAGTTCTCATAGGCCACTTAAGAACAAGCGGGGGAAACCCCAAGGATAATCAGCA
151->TGGAGGACAACTATAGCTTACAACGTAACTAGCGAGCAAGAACCTGTCAGGCGCGCCTTACCGTAAACGCACCCAGCCCTAGTGACGAGCTAACAGAAGCTGCTATTGATTAAGTTCATGTTAAAACGCCGAGATTTCCGGGCCGATCCC
151->CTGTACCTCTATCATCCGATGCCTGAGGATTGTTTCAAACTACGTCCGGAGAGCCTTTAGGATGGACCGCGCAAGATTAAGAGCTGCTTGAATGTCAGACGTTAAGCCGACCGGCTCTTGTACTTGAATTCACCACATTAGTTCTATTGT
152->ACCGTAAACGAAAACCTGCTCGTCGCGCTTGATTAATTGTCATTTCTCGGACATGCAGACCGGATAAATGTGGGAGGATATGACCTAGTCTCCTAGAATGAAGGATGTGTAAGTCGCGGCACGAATTCTTTTACGTTCACTCATCCTGAC
152->CAATTGACGCTCTGAGGACAGGTAACAAGAACGATAATAGCGGATTCATGGCAAAAAAAGCAACCTAATCACTGGCCCTACGATGATTAGTACACAATAATCGAAGACCCAATACCATTATTTATATGATGGAATGGGTTTCCCCCTAGT
153->TTCTGTTTATCTTACATTGAACGACACCATCCTGACGCTCTGTGCGCAACGAACAGGCATGGAGAGCCGTGGTCCGGTTGGACAGAGAGCACGCTAACCTGCCGTTGGAACAATGTGGGCATCAATATTCTGTGGAGGCCCTCGTCAATA
153->GATGGGTGAAGCCCTTAACTAGAGGTGCGGCTCAACAGGTCCTTGTGTAAGAATATCTCGCCACGACCTGCCTTCTTTCATAGCTCCTTAATAACAAAAAGCTGAGACGCGTGTCTTTCATGACGACTATGGACCCATGCGATGCCAGCC
154->TAAGCGCCCATACTGATCACGGGCCTACCATCCAAACGGCAGCGAGCAACACAGGAGGCAGTCGATACGTGGAGCCAAAATTAGCATTATGCAGAAGTAGCAGCTTTGACTGCAGTTAATCGATTCCTCACGCACAGAGGATCATCCGAC
154->CCGGCCTCGTAATAGGACCTCATTGGGGACGATTACTACACGTAAAGTCTTGAGCATCCCCTCATTCTAAACTACTAATCCACCATGACACTCTGTAGCTTATATATTGGACCTCGCCTTAGTTGAGTATTGGTTCGTAGGTCGGCCCAC
155->CTAACCACAGGATGCTCTGATAGATGTTTTGGTGGTGCTCCTCTTTTGGGTTGCTAAAGTCATTTTTCGATAGTTCTCCTCTGTCGCACCGTAGTAGATTGACGTTCTGGTGCATGGCGAACGTGGGCCGGCACTACTGTAGTGGTGGCA
155->TCAGGAAGACGGCTGCAAGTAGCACTCGTCTCGCGAACATGGCACTTCGGCTGCCGGCACACAGCGGATCCGCAATTTTTGGTAGAAGAACAGTATATAGCGTATGCAGAGGTACACAAGCTCGCCGGATATGCCATATGCCCCTGGTCG
156->ATCGTGCCATCTCGGGCTGTGCGCACGTCCGGCCAAGCCGAATACCGGAATTGGAGGTGGGAGGGGATGGTTGAATGCGATTACGTGCAGACCATTAGCGCTCTATTGACAAGGTTTCCGTGACATCCAATGATCGTCAAGTACGCCGGG
156->ATACAAGATAATTAGGCAGGCTAAGTGCGACCAGTACTCTCGTTGAACCCGCCAATTGCTTACATGAATAAGCGCGGTAGCCAATTCTTTGCACTTGTTTGTAAAATTTATGCCCATATAGAAATTATCCAATAGTCTAAGAAAGCGATG
157->ATCCCGCATAGACCGAGTTCTGCACTCCTGCCCTAACCTAATGCCGTCTCTGAAAGTGTCTGCCGGGATGTGCCAATGACCCTGATATGAACCTTGCTATGTGCCGACATACGGGCGGTGGCCCTGTCGTTACGATTCAGCTGTCTCACC
157->GCTCTATGAGGGATGTAATGTGTAATTCCTGGGAAAACGAAACGGAGGACAGAACATAGGGTATGCGCGCACGATAGGAAGTGCTGGTTGGCCAGTAAGGATAGTAGTACATCGCCAAGTTGATAGCGCAGCCTCACATTGCCGGCTTGC
158->GTGCTATCACCTTCATGCATTTGAACGGTGTGCCGTGACCACTCGGACGTAAACGTGTTTGTCAACCCCTCCAGGATTGACCATTTGGCGCAGAGGTAGGATGGGTTGCTCGCACTGTGAGTAGACAACTTTCAATGCACTCCAGTAGGA
158->GGCATTCCTGTGTACCTCCAGAGCTTGGTATCGAAACCCGTTTCCGGATACTAGCGCCGGAACGGGCCTTAAGAACATCAGTAATACACTTAAACGGCATAATCGTCCGGCGCGATGGGTATCACAACCTTGGGATCTTCCATTTAAGCC
159->GCTGTTGACGACAGTATCACCAGGTGCGTGAACGTTGATTGATGGTAGGACCTCGGTTGTCCGGCGTTTTACTCGCAAGGATATGTTCTCCACTCCTGTGCAAAAAGGTTATAGCAGACCACGTACTACGGGGTTCCGCAATAATTAGAC
159->CCAATGTGCGCCATCAATTGCGCCAGAGTGAGCGTCGTGCGTTGGCTTTTCAATATTTGGGATATCCGAACACTTGCCCCGTTCCATGACGTGGCCGATAGAAGAGATGGTAACAATTTGGCCCGCACGGTTGAAGCCTGGTAGGTTTGT
160->AAGACATTAGCCGAGGTTTTGATGGTTCTCGGTATTGCTAAAGGTCTTGAGATAACCTTCGCCGCGGCCTCGCGCGCTTCTAGATCCTAACTGTCGACCATGCTACATGGAAGTCCGGCGTGTAAAGATGTGCTCTGCGTTAACCGACTG
160->GCGGATACAGGCTGGAAGTGTGGGCAATACACTCAGTTACAGGTGACGTCCTGACTCTCTCAAATCTGGGCGGTATAGGGCTAACTACTCAGTAGTAAGGCAGTCCCTTGACCGTTCAATATGTCGAGCTAGAATTAGTGGAAGACCAGA
161->CAATGAGAATTAGCCCTAATCCATGCTGACAGGCAGTTTACGAAGCCGGGCGCGGCTAGTTAGAAGACGGAACATAGTCATAAAGATATTCGAATGGCTACCTTAGCCGTACACGTTTTTCCCAAACCCTTGACTCCGTGCACATGATTG
161->ACGCCAGGTGTTGGTTCAGTGGATGACTACACTCCGATATAACCGGTAAGGACAGCGTTGTCGTAGTGGCTGTCGAGGTCACGACATCCTTTTGCTCGACGCTAGATGTTATAGGCGAGGCAGCTTATACTGGTGGGACGTTCAACTCCC
162->CCCAAGCCAGACACGAGTGCACATTGTGACCGCTATTTAATCCACAGTTAATCGGATTCTCACACCGTGAAGAGGGAAGTCAACGTGCTGATAAGCGTGTCGCTGTGGCGAATCGCAGAGAGGCGATCACAATACCCTTACACGTCTTGG
162->CGTGCAGCAGGCTTTAAATTTCTACTTACGACCAATTTCGTGACGCAGTTAGTATCTGCTCCGACCCGTAATTTCGCGCACAATCATCTGGGAAATTCTTTCCGGCGACTACTCGAAGTTATGTCGTAGATTCGTGAGCTTTAGAGCCCT
163->CGAGACAATGGGCCATGACACAGAAAGGCTGTTCAATCTTGACGTATGCCCCGGCAACAATATATGAATATAAATTTTATTCGTGAGATGGCTACACTTACCGTATGACCCTGAGACGGACAGAAGATAGTCGTGCCAGGACGATAAGGA
163->TAAGATCAACTCACCGCAGACACAGCCAACGGCGTGCACTTACAGGGTTGAGTGAAAGGAAGGATCATAAGCCAGGGGTGCGGAAGAGAGGGCGAGACGACGACTGCGAGGGATGATAATAAGCGAACGTATTGTCCAACTGTCTTGTAT
164->GTGGTCACATGCCTTCATTGTCCATAGCTCTAGTCAAGTCCGGGATTCCTGGGGACGCAACTCTACCAGATGTAATACCAGATCGCTTACTAGGGGATCCGAGTACCGCGCCGTTGACAATAATTTTCCCAGTCTGACTCCATTGCTTCG
164->GATTGTCGGTCAAACCAGCTCGCGGATTAAGACCATTTCCTTTAAGTAAGCCACACGCTAGTACGGCCACACGATGTCAACCCTATGGGGCTGATCTGTGAGTTGCCGCTTACTCATTACGTGCCTTCGTGGTCCGAAGGGTAAAGAGAA
165->GGCACTCGTTCCGAGACATAGTAATACTTGGAATATTTATACTTATAGTGTAGATGTACACCTTATAGAAGGACTATGGCCTTCATAAACACATTTAAGTGTCTTTCGCCCCAAGCAACAATGAATCGTCTGTACTTTTCGCACAGAGCA
165->TACATATCTGAAGCTGTCGTGTCATAAACAGAAGGGATGTCTTTGGCTTCTCGTTTGTTGTTACGGATTTCGGTGCCAGCTGTTTCGTTCTAACTGTGGAACAGCGGACATTTTAGGGGCCGTGTGTTTGAGGCCCACCTTAGCATCTTG
166->CCGATCATCACATCGCCTTCGGAATTTATCGGGAATGGCCTATCACAGGCTCTCCTGTAGGTGGGAGAGTCATGCGAAATGTGGATAGTATTTTCAACCACAATATGGCAAGGCACGAAGAAGCCTCTCTCAGATCTGTTGCTCGCCCCT
166->CACACCGGAAGGCGCGAATAAGGAGGTGTTAGTGTTCTACCTCACGGTTGTGTCAGGTCGGCATTCCACCTGCTGATGGTCGTTATAACGGGTAATGACAACCTTGCCGCTCAGAGATTGAAGAGGGACAAGGTAACTGGCATGTCTTGA
167->CTTATGGGTGGGGGGCGCACGCGTTCCCTATTGGCGATTAATAATGTCATGTGTCCGTCATACGTGGTTAGTACCAGAGCGATGAGTAGTATTCTCGACGGCGCAGGTTGGCCACGTCCGGCGCGCCAGGTCCGCCGCCGCAGTCATTAA
167->CCTCTAGTAATGAATATGTGGAACTGATGAGTGTCCAAATAGCTTGCTTCCGTTCCATGAGTTCACGGACCTTGCGTAACCGTGCTTCCCCATCTGATATAACTAAGAGATAAAGGAACCAAGACTGACGGCCTCGCTAAAGGGAGCACA
168->TTCTTATCGGCCAATAGCTGTAACAGGCTCCGTAGTACATTCGCAGCAAGGCGGCCCCTAACTGTTGTGACCGCACGATACGGCACACCGGGCAACTCTTTGCCCGTCCCAAGCCGGTTTAATGCCGTAGCCAACGCAATGCAGGCGGCG
168->CCCTTGCTCGTCCCGAACGTCGCAACGAGGCCCAGTGCAGTTAACGTTCACTTCTGATATTCACCAAAGTATAACTACTTCGCTTACCAGCTAGGCTACGTCCTGTGTTTGAAAGACCGACGGGGATAGTTAGCAGAGGAGACACCATGT
169->AACGCACTGTTTCCGTAGCCTATCGTCAGGGTGAAAGCGAAAGCTTTAGTACCCATCTGAGATGGAAATATGAAGGCGTCTGCTATGGTAGATGGCGACAGACGACTAGATTGATAATTGGGGGGGGTTCCAGAAGAAATGAACAGGGAA
169->CCAGGCCGCATAATGATGTTTGGTGAGAATTTAATCTCTAACTTTTACCTTTCCGACTACCCGCTTGCTATCAGCAGTTGATATCTGTCCTACCCTGCATAGCGTGATTACGGGTAACCTTTCCACGAGAAACGGTCGAACCAGGTTCGG
170->GTGATTGCGCATGTCGATTCCCGCCTACCTTCTACAGACGCGGCTCAAACGGGAAGGCAGTGTCACACCACGATTCATAGTGATAGGCGACTGAGTGGTTTATTGATAGTAGTACTAATTATCGAAAGGGGTACCGACCTTCTCCAGAAA
170->CATGGTTTCGCGATACTCCTTGCGCTCGTATAATATCGGGACCGACTGTAAAAACCGGTAGGAGTTACCAGGACCCTATGTATGACACTCGACCACGCAATGATACAACACATCGTCAGTCTATGACACCAATATTATCCGCACGTGCTA
171->CAGTGTCAGCATTTGCAAGTCAATCCCATTGCCTAACTCGATTTCGTCCAACGTATTTACCCTCTGAACGTCATTAACGCCGACCCGGTTTGTCGCGTCCAACTTATTGATGTGTCACTCCACACTGACAGGTTTCAGTACAAATCCTAT
171->GGGCGGTAGGGACACCTGTGTTTGTACGTGTTTGGCAAGCTAGTCCTGACCTTTGGTGCCGGAAAAGACCGCTCCGTTGCTACATGGGCAAGAATAGCGCAATTCTGTTGTAGGCCGAGCCCGAAGAGTGAACCGAGCCGGATGTCTTCT
172->CACGTCGTCGATGTTGATCCTGCGCAGATAGCTAACATTCTCGTTATGACTTCATATCAACGTACCTCTCCGCACCCAAAAGATCACTAAGTGCATATGAACTCCTCCGTTACAAGACGAATTTGTTCCACTAACTCCCACACTAGGAAA
172->GGGGTTATACCAACCAGAAGGCAGTTCAAGAGGCGGAGGGTAGTAAACCATTAATTCCGCTCCGAGGCTAACTTGCCGGAGTCGAAGTCCCTTCAGCAGTCCGCATTCTACGCGAACTTTACCGTCATACGAGCTTCCCAAACCAGGGCA
173->CGATTAGACATACGCAGATTCACGAGAGACGAGCAGTGAAGAAGGACGGAATACAAGCAGCTAGCCTCGAGCGGCACACCCCGTCTGGGAGAATCATCGAGCTCAATCAAAATCCTTTTAACTGATACGGTCCGACCCATTCAACGATCG
173->TCCCTAAACGTCCCTACGAGCTTACGTTCTGGTCTCACCCGTGCCAGTGTATGTACCTTCCCCTCATAACCCACAAAAGAAGTGTGACACTTCTATCTCATGGGCACCGTGACCCCTAAACTAGAAACTCAGTACAACCACAGAACGTAA
174->AACAAGGATGCCTGCCGCTGTACCACCTAAATTAGGATCGTATCTGCCTCTCGTAGGAATCTATGTAGGAATACAAGAACTTGGCAACTCTTATCTTGGTCCGGCGAAGTATGACGGGAGCCCTAGCTCACAGTCGGATTTTCCTAGTGA
174->GCGCCGCGCGGTTTCCGGTTCGCATAAATTTTCGGTATGTGGCGCCTGTACCTTGTGGTTTCTAGATCTGACGATAGGGTGTTAACCTTGCTGCCGCAATGCTCTCGTCCCCTAGCCCGGTTTTCGAATGCTAGGTCTGGGACTGCAAAA
175->GAGGTTTCAGAGGCAGGATAGGCTTACTGTGCGCCGGCCCTCTCACGAGAGTAGAGCGGCGACGCCGTGACCAGCCGCGGGCAGGAGACAAGCTCACTGGGCCGTTTACGGTTCAAGCTAAGTGCGAGCGAGAAGTATTAGTAGAAAGTA
175->AAGCCATTAATCCCATGGCTACTCATTCTGGCGTGTTTTGAGGCTCTACGAAACCGCACCGCTCTTGCTTATTATCGGGCATTCAGTTGACGCTTATTGCGCCAGGTAATGCATCCTCTTTTTCTTCGGTCGAACTAATGTGGACCCCCC
176->GGGAAGTGTCGCCAATGGTTTGGACCCTTCAACTTCCCACAACGTTGCCAGCTATGCGAGAATATGTTCGTCGATCACAGTGTCGATAACCCCGCTATGTCAGGTAAAGATAATCGTATGGGGCCTGGGGCACTTTGTGCACAGAAAAGG
176->CCCTAGGTCTTTTTGTTGAACATGCACCAATCCTTCGCGATTGGTCGCTACCTATCGGCGCGTCCTTACGATAGCACGTTTTTTACGATTCCCCTAATTCGAGATCGCGTCCTGTAGCGAATGTACACCCTATCTTTGTCCGATTCCGGG
177->CGGCAAAGTGATACAGGTTACATTCAGTAGCTTAGTCTAGCGAATCGAGTGTCGTATCTAACCGGGGATGACAGCGTGAAGCCCTGCGGGCGCGAAGATTTTGGCCGCGTCGTTTTCGCGGGTGGGGCTAGTTTCCACCAACCCGCGTTT
177->AGTATGAAGTTATGCATTTACTGAAGAAGTTTTACGAGTCATACGATTACAACCATACGCCCGCCTGTTCTGTACTGCGGTCGCTGAGCCCTTATTGAAGCCCTTCTAAGGCTGAATAAGCCGAAGAAGATAGCTGACTCGTGGCGACCG
178->GTCGGGACACTCGACATTTTCGCAGCTTGCAAGGGGTCTACGGGTCACCGAGTAAGCGAGCGCGAGTGCAGAAATGTCTGAGCTATTCGATCAATTACGGTCCGCACACCGTGGCTAATGCGGGAGTAGAATTATAGTAGAAAAGCTCCG
178->GCCTCCGCGCAAAGTATGGTGGAGTAGGTGGCTTCATGGGCAGCTTTAGAATCTCAGCGGGTGACCGTACTCGAAATTGGCCTCTCAGGTATAACGTTACGGGTGGCTGCGTCAAAGGGGGACGTTCTGCACCAGGGTAACTCGTGCCTC
179->GAAGCGGTTCCTCGTCAGGGTAGAATGCATTACTATATCGCTGTTAGTGAAACATCAGGAAGTGAAAAACGGGTCTGAACATGTTGAGCGAATTAATGCCGCGATTGGACATCGTGAATTTCTGTTAAACAGATGTGAAGCAGGAACACA
179->GATCACGACCGCACCACGTTCCCTCCGTTAACCCGTCAACGAAAATTATGCGCTATCCTCCACGTGCCCACGCGTACCTCAGGCTAGTGGCTTCAGTTGTAAGCCTGCATGATCCGGTACGGCCCAGTACCTGAAGTCAATGTAGAACGG
180->ACTGCCAGTCGGTAGCCGATACAATTCAGCGGAATAGAGTCGTTTTCACCCCGCGAAGGTAGAATACTGCTGTAGCGGCATACGTTATACAAGATAGGTCGAAAATATGCAATTTCTTATCGGGATGTAAGCTTGGGAGACTGGGGAGTT
180->AAATCGTGGAAACTAGCCAGCGGCTGATGGCAGTTTAATGGGAAATACTTTCCGGGCACAGATCGACGCATGGCACGTGAAATCACGTCGATTGGAGCTAGCCCCGTTAGAACAGGCATCGAATGGGGCCCCCTAGAATCGTGACCTATA
181->GTAGCCCAGCGCATCCAGATCGGATGGGAGATACTGAGCGGATGGCACACTGCCCAGCCTACAGCGCTTTTCGAGACGCCTTACTAGTCACGGTCAGAATGCCATAAGGTAATTCTGTTGTATTAATTCGCTTGACGTGATTATCAACGA
181->TCCGGTCATTCTAGACATACCACTTTACGTAGGAACAAAGGTCGCCATGAGCCTATATTGATCTCACACCGCCGCTCCTACAATACCGTTTCGTGGTACTGTGATGGTTCATAATTTCGGTTCTTGGCCTCGATCGAACAGGTGACTGTG
182->AGTGGATGCCTCTTGCATGCTAGATCTCATTGGTCACGGAGCACCCTTGCGACGCACCAACACGCAAACGGCACCATGACCTGACGTGATTGAGCTGCGGGTGGTTAGTCACTGATTCTGTAGTATGCTGCATCAGTGGTCTTCCCAGAA
182->AATCCGCATATTAAAGACACGGCTTAGTCACAAGGTCGCGCACCCAGACCGGTCTTATGTCGGCTAGTAGACCAGTGGGCACTACTGCTGAGGACGTAATCGTTATCATGATACGATCCAGATAAGCAATTGATAACAAACGGACTCTTT
183->ATTCGGACCGATTGGCGGCGTAAACTAGTCGTTTGGCTTGGTTTGATCCGAGCATCGTACGATACTCTGTACCCTTTGTCATTGAATGCTAGGAATGGTTTAGTGGTGTTAAAGTTTGTGAACCAGGTTGCATTGGTCCCAAACGGGTTT
183->CACAGCCACCGCAATCTGAGTTTTCAGCACGGTCTATAGTAACAGCCAGACTGTCTGTACTGCTCTAATTACAGAAAAATCTTGCTCTCACAGCGTTAATCGCGCTCTGGAGTTTGCATTGCGCTCCAATCAACCTTATACCTATACGCC
184->ACCGCTAGTAATACAACACGAGCATGGCTGTCAGCCTAGGTGCCTAATCATCTCGAACTACTCAAATACACTCAACTCGTAGACCGCGTGCATTCGGAGTGGATCCGTGGACAACGCTATAGCTACGCCTCCGAGCTGTAAGAAGCATGT
184->ACTCGTAACGCGAGGAGTGCTTGATAAAACAACTCGCCGAAATACGAGTTTCAGCATTGGACGTCATGACCCTAGTCGGGACCGATTAATTGCTCCTCGAGCATAGTCGTGAATCTATCCACGCAATGGAACGCCGTGTTGTACAACTGG
185->CTTCCCAGTTAAAGCGGTTTAAGGTTAGCATTCCTCATTTGTTATCTCCTCGATTGCAATCCATCGGGGGTGTTAGACGCTGGATCTCCTCACAGGGGCGATATCGGGTCTTCAGTTACCAATCCCACTGAAAGCATACCGCCATCATAT
185->GAGCCATGGATCGGATAAGAGAGTGAGGACGTGATGCTTTCCTAGCATCTTTGCTCCATTGGTGTAGTGCTTAGTGAAGTTATGGTGATTTGCACCGTTGCAACGGTTTTGTGACGTACCCACAAGGCGACCGGATCTGCTTTCATCCAC
186->CGTACAAAGATACGTGGCTCCCTTTTATGCGGGTCAAGCCTGCGCTTAGCCGTCGTATCACTAATTGCATGGAACCAGCTAGCACGGTCATACCAAATCGCCTTCTACATTGCCGTAAAAGCGTCTGCTGGAACTAGGGTAGCGAGGCTG
186->GAGAATCTGTCATACCCGAAGGGTCTGAATCCGAGTCCTAGTATCGACAGTATAGCGGGATGCTGTCACGTAGTACTTGATCTAGTTCCAGGCACCCTGGCTTTAGTTAAACAGTTGGTGAATGCCATACTAGGAGCGACTTCATTATGT
187->GCGTGTGTGTGCGAGTCGTGGTAGTGGGTCTAAGCCTAGGAGGACGCAGACAGGCAGCACTTGGCAAACTGACACCCCTAGCCTCCGTGCTAGGCCCAATGAAAATTCGATAGGCATTCCTTGTAGATCTTATTTTGAAGGATAGCGCTC
187->CTATCGTAGCAGGTCAGTCTCTCTAGCTCCTACCTTGCAGTATTTTAGTGGCCCAAGTGCCCCGCTTGGTTTCAAGTATAGAGAGGGGTGTCTACATTGCCAGCGCAACCGGCCTAGCATCCTGTTGAAGTCTACAAGCCTCCGCTGCAC
188->AAGAAACACTACGGGAACGCAATAGCTCGGCGGTGATGATGTTAGCTGCTGTAGATTAAAACTACTTTCCTAAAGCTCCCCTATTATATTATCAAGCTTACTCTGCACCAGCTAACTCGCAAATAGGCTCTCCTCCTTACTAGTTACAAC
188->TATCACGGTTTTATGCAGAGTTCCTTAGGCATTTTCTACATAGACATTGAGTAGGGTGTAATGCCCGAGTATTCCTGATTAGAGAACTCCCAACAGTTAGACTTGCGCCGTTGCGGAGTCTAATTAGTGACTACTTTCCGCGCGTTTATG
189->CTCGGGCTTTCTGGCCGTGCCTCTACTGCTGGTACACAACTTCAGACAAACTAAGGTTCATGTCGGGTCAGATACCCACCGTTATGGTTACGCCAGTCCTTGCTTTACTTAGCCGGTTCCTTCTTCGTCCAAACTTAACTAGTCTTAGAG
189->TTAATAGAGGAATCATGCACCAGACAGGCGTATGACTCGGTACAGCTATAGACGCCCTCGAAAGCCCTCTTCCTGCCAGGCAGGTACTTCGTAATCGAAGGATTTTTGACGGTCTTAACAAAGAGTTCTTAGTCATTTACACTGTATAAG
190->GCCTGAGCAGAAGGAAGCTTCATGCTGCCCGCTCCCTAACAGGCCGAACGAGATATTGATCGACCGCTATCTCCTGTGGCGTATAATCTACTTAGACTGCGAGGGCTTATTTTTACGACGCCACTATCGATTCTTCGGGGAGCGACGGGT
190->ACGGCACAGCTTCGGCAGGGCGCGAGTTCTAGTATGTAACAGAATAGGCGGTTCCGAATTGGCAGGACACCTTCTCACGGAGCGCCAGGCGATTTAACCAGCACCGGCTACAGGATCATTTTGACTGCTTCGTCAGGCCCAGTGAACGCT
191->AGTTGTAATAAGGATTCGAGCGTGTTCACCCCCTGTCTACCGTATTAGCTCTACTCTGAGTGGTCCCGCCTCTGATACAGCAGTCGCACAGGATGCCTTCGTGGTACCACTCCGCAAGCGACCGACCCGAGCAAGGAGCCTATGTTCGTG
191->GGAAAACTGAGGCTTTTTAATGGCGGCCTACGAGCTCTTGGAGGTGAGAAGTAAGCCTACCGGCAGCTAACATATCCCGTGCGATGCGTATCGGATGCAGTGGCTAGGCTATGGGAGGAATCCATGACTGTGTACTAGTATGAGGACGGC
192->163
192->178
193->143
193->133
194->151
194->182
195->184
195->190
196->172
196->183
197->160
197->169
198->174
198->189
199->173
199->177
200->188
200->158
201->166
201->176
202->181
202->186
203->170
203->191
204->187
204->145
205->149
205->131
206->154
206->141
207->137
207->139
208->179
208->148
209->140
209->159
210->162
210->164
211->142
211->129
212->152
212->136
213->156
213->185
214->150
214->134
215->128
215->167
216->138
216->171
217->155
217->157
218->180
218->146
219->147
219->153
220->135
220->175
221->144
221->168
222->132
222->165
223->130
223->161
224->220
224->212
225->207
225->197
226->219
226->217
227->209
227->205
228->201
228->223
229->210
229->206
230->211
230->222
231->199
231->192
232->208
232->194
233->196
233->195
234->198
234->221
235->193
235->218
236->202
236->216
237->214
237->215
238->203
238->213
239->204
239->200
240->236
240->231
241->238
241->229
242->224
242->227
243->225
243->237
244->226
244->234
245->239
245->232
246->233
246->235
247->228
247->230
248->247
248->246
249->244
249->242
250->243
250->245
251->241
251->240
252->251
252->249
253->250
253->248
254->252
254->253
'''

sInput = sInput1
BASES = ['A', 'C', 'G', 'T']
INF = float('inf')

def HAMMING(s1, s2):
    score = 0
    for i in range(len(s1)):
        if s1[i] != s2[i]: score += 1
    return score

def PRINT_TREE(tree):
    for edge in tree:
        print('%s->%s:%d' % (edge[0], edge[1], edge[2]))

def WRITE_TREE(finalscore, tree):
    with open('221018/221018_Q2_output.txt', 'w') as f:
        f.write(str(finalscore) + '\n')
        for edge in tree:
            f.write('%s->%s:%d\n' % (edge[0], edge[1], edge[2]))

def ADD_EDGE(tree, st, ed, dist):
    tree.append((st, ed, dist))
    tree.append((ed, st, dist))

def PARSE(sInput):
    lines = sInput.strip().split('\n')
    n = int(lines[0])
    root = 0

    lstLeaves = []
    dicChildren = {}
    for l in lines[1:]:
        parent, child = int(l.split('->')[0]), l.split('->')[1]
        dicChildren.setdefault(parent, [])
        root = max(root, parent)
        if child.isdigit():
            dicChildren[parent].append(int(child))
        else:
            new = len(lstLeaves)
            lstLeaves.append(child)
            dicChildren[int(parent)].append(new)
        
    return n, len(lstLeaves[0]), root, lstLeaves, dicChildren

def RIPE_NODE(visited):
    global dicChildren
    for parent in dicChildren:
        if visited[parent]: continue
        else:
            child0, child1 = dicChildren[parent]
            if visited[child0] and visited[child1]: return parent
    
    return None

def DELTA(c1, c2):
    if c1 == c2: return 0
    else: return 1

def MAKE_RIPE(c0Score, c1Score):
    score = {}

    for base in BASES:
        score[base] = min([c0Score[c0base] + DELTA(base, c0base) for c0base in c0Score]) + \
                    min([c1Score[c1base] + DELTA(base, c1base) for c1base in c1Score])
        
    return score

def SMALL_PARSIMONY_CHAR(n, root, lstChar):
    visited = [False for _ in range(root+1)]
    
    dicScores = {}
    for node in range(root+1):
        dicScores.setdefault(node, {})
        if node < n:
            visited[node] = True
            for base in BASES:
                if lstChar[node] == base: dicScores[node][base] = 0
                else: dicScores[node][base] = INF
    
    while True:
        v = RIPE_NODE(visited)
        if v is None: break
        visited[v] = True

        dicScores[v] = MAKE_RIPE(dicScores[dicChildren[v][0]], dicScores[dicChildren[v][1]])

    return dicScores

def BACKTRACK_HELPER(base, score, c0Scores, c1Scores):
    for c0base in BASES:
        for c1base in BASES:
            if c0Scores[c0base] + DELTA(base, c0base) + c1Scores[c1base] + DELTA(base, c1base) == score:
                return c0base, c1base

def BACKTRACK(root, dicScores):
    global dicChildren

    dicChar = {}
    for node in reversed(range(root+1)):
        if node not in dicChar:
            minChar = min(dicScores[node], key=dicScores[node].get)
            dicChar[node] = minChar
        
        if node in dicChildren:
            c0, c1 = dicChildren[node]
            c0base, c1base = BACKTRACK_HELPER(minChar, dicScores[node][minChar], dicScores[c0], dicScores[c1])
            dicChar[c0], dicChar[c1] = c0base, c1base
        
    return dicChar

def TREE_CONSTRUCTION(node, dicString, tree):
    global dicChildren
    if node in dicChildren:
        sNode = dicString[node]
        child0, child1 = dicChildren[node]
        sChild0 = dicString[child0]
        sChild1 = dicString[child1]

        tree = TREE_CONSTRUCTION(child0, dicString, tree)
        tree = TREE_CONSTRUCTION(child1, dicString, tree)
        ADD_EDGE(tree, sNode, sChild0, HAMMING(sNode, sChild0))
        ADD_EDGE(tree, sNode, sChild1, HAMMING(sNode, sChild1))

    return tree


def SMALL_PARSIMONY(n, root):
    global lstLeaves

    dicString = {}
    finalscore = 0
    for node in range(root+1):
        dicString[node] = []
    
    for m in range(len(lstLeaves[0])):
        dicScores = SMALL_PARSIMONY_CHAR(n, root, [leave[m] for leave in lstLeaves])
        dicChar = BACKTRACK(root, dicScores)
        finalscore += dicScores[root][dicChar[root]]

        for node in dicChar:
            dicString[node].append(dicChar[node])

    for k in dicString:
        dicString[k]= ''.join(dicString[k])

    tree = TREE_CONSTRUCTION(root, dicString, [])

    return finalscore, dicString, tree
        

n, m, root, lstLeaves, dicChildren = PARSE(sInput)

finalscore, dicString, tree = SMALL_PARSIMONY(n, root)
WRITE_TREE(finalscore, tree)